"""first

Revision ID: acb6ef3c3656
Revises: 
Create Date: 2024-04-29 18:48:15.409202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb6ef3c3656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_track', sa.String(), nullable=False),
    sa.Column('name_img', sa.String(), nullable=False),
    sa.Column('url_track', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_img'),
    sa.UniqueConstraint('name_track'),
    sa.UniqueConstraint('url_track')
    )
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('users_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracks_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracks_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'tracks_id', 'users_id'),
    sa.UniqueConstraint('tracks_id', 'users_id', name='unique_users_tracks')
    )
    op.create_index(op.f('ix_users_tracks_id'), 'users_tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tracks_id'), table_name='users_tracks')
    op.drop_table('users_tracks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
